### ISSUE TITLE
您好，训练时遇到一些问题

### ISSUE THREAD

**Issue by chenlanzheng** [chaofengc/Face-SPARNet#17]
RuntimeError：Stack expects each tensor to be equal size,but got [3,128,128]  at entry 0 and [3,1024,1024] at entry 31

用的是celeb数据集，请问作者您遇到这种情况吗？

**Comment by lanyingyuexi** [comment]
> RuntimeError：Stack expects each tensor to be equal size,but got [3,128,128] at entry 0 and [3,1024,1024] at entry 31
> 
> 用的是celeb数据集，请问作者您遇到这种情况吗？

我也遇到了这个问题，请问您解决了吗？万分感谢您的回答
