### ISSUE TITLE
It is possible to train SPARNet and SPARNetHD models on Google Colab ?

### ISSUE THREAD

**Issue by iamhoanglong** [chaofengc/Face-SPARNet#20]

**Comment by chaofengc** [comment]
SPARNet trained for bicubic downscaled inputs generate128x128 HR images. Therefore does not need much computation resources, and should be able to train on Google Colab.
As for SPARNetHD, it needs at least 25GB memory to train with batch_size=2 and 512x512 outputs.

**Comment by iamhoanglong** [comment]
thank u
