### ISSUE TITLE
attention map visualization

### ISSUE THREAD

**Issue by yjwnet9** [chaofengc/Face-SPARNet#22]
Is there a code to visualize the attention map?
<img width="445" alt="캡처" src="https://user-images.githubusercontent.com/109531833/190561316-cea2c4ac-4441-4560-bb5d-86676e9257e5.PNG">

**Comment by chaofengc** [comment]
Sorry that we have no plan to provide codes for attention map visualization.

**Comment by cyyycc** [comment]
> Sorry that we have no plan to provide codes for attention map visualization.

I see. Thank you very much!
