### ISSUE TITLE
训练集问题

### ISSUE THREAD

**Issue by 1530537501-jst** [chaofengc/Face-SPARNet#24]
作者您好，我用官网上align CelebA 的数据集进行训练，效果不理想，想问一下作者可以提供一下训练数据集吗，万分感谢。

**Comment by chaofengc** [comment]
图片并没有经过复杂的预处理。利用[mtcnn](https://github.com/kpzhang93/MTCNN_face_detection_alignment)检测人脸bounding box，适当扩大即可。最好是自己写脚本处理。

这里有一个版本，由于图片版权的缘故，[下载链接](https://connecthkuhk-my.sharepoint.com/:u:/g/personal/u3003628_connect_hku_hk/Ef7siKyLDoVLleMY3zX6PT0BfoE0ROrDSHUCoVdWPV2EzA?e=86FGCm)是临时的

**Comment by 1530537501-jst** [comment]
> 图片并没有经过复杂的预处理。利用[mtcnn](https://github.com/kpzhang93/MTCNN_face_detection_alignment)检测人脸bounding box，适当扩大即可。最好是自己写脚本处理。
> 
> 这里有一个版本，由于图片版权的缘故，[下载链接](https://connecthkuhk-my.sharepoint.com/:u:/g/personal/u3003628_connect_hku_hk/Ef7siKyLDoVLleMY3zX6PT0BfoE0ROrDSHUCoVdWPV2EzA?e=86FGCm)是临时的

好的，万分感谢

**Comment by cyyycc** [comment]
> 图片并没有经过复杂的预处理。利用[mtcnn](https://github.com/kpzhang93/MTCNN_face_detection_alignment)检测人脸bounding box，适当扩大即可。最好是自己写脚本处理。
> 
> 这里有一个版本，由于图片版权的缘故，[下载链接](https://connecthkuhk-my.sharepoint.com/:u:/g/personal/u3003628_connect_hku_hk/Ef7siKyLDoVLleMY3zX6PT0BfoE0ROrDSHUCoVdWPV2EzA?e=86FGCm)是临时的
作者您好，请问您能提供一下测试集么？万分感谢！！

**Comment by chaofengc** [comment]
测试数据集已经在readme里面的百度网盘以及google网盘提供
