### ISSUE TITLE
attention map visualization 

### ISSUE THREAD

**Issue by cyyycc** [chaofengc/Face-SPARNet#25]
I try to visualize the attention map, but the result is not as good as that in the paper.
my result:
![image](https://user-images.githubusercontent.com/101498078/201889268-c85bffdf-d39b-4852-8b3c-da4fe8e70217.png)
your paper:
![image](https://user-images.githubusercontent.com/101498078/201889440-e81b4664-f7d1-4fd0-962b-259148d65cf8.png)
Can you publish the code to visualize the attention map?
Look forward to your reply, thank you!

**Comment by chaofengc** [comment]
It seems that your visualization is correct.
Please note that the spatial attention is learned implicitly without ground truth supervision. Therefore, it is difficult to get perfect attention maps. Figures in the paper are manually selected for better illustration. 
There are no other tricks to visualize the attention map.

**Comment by cyyycc** [comment]
> It seems that your visualization is correct. Please note that the spatial attention is learned implicitly without ground truth supervision. Therefore, it is difficult to get perfect attention maps. Figures in the paper are manually selected for better illustration. There are no other tricks to visualize the attention map.

I see. Thank you very much!
