### ISSUE TITLE
训练集问题

### ISSUE THREAD

**Issue by lanyingyuexi** [chaofengc/Face-SPARNet#26]
请问可以提供一下训练时的数据集celeba_crop_train吗，之前的链接失效了。万分感谢！我是直接用的img_align_celeba，不知道可不可以，但是现在会两个错误：1、RuntimeError: Caught RuntimeError in DataLoader worker process 1.  2、RuntimeError: stack expects each tensor to be equal size, but got [3, 128, 128] at entry 0 and [3, 218,178] at entry 22. 请问您有遇到过吗？

**Comment by chaofengc** [comment]
以下是有效期30天的链接: 

链接：https://pan.baidu.com/s/1_vmxS23BJ5v4Zf84NCH9fw?pwd=y76c 
提取码：y76c 

运行错误看起来是数据的问题，img_align_celeba的图片大小不固定。

**Comment by lanyingyuexi** [comment]
> 以下是有效期30天的链接:
> 
> Here are the links that are valid for 30 days:
> 
> 链接：https://pan.baidu.com/s/1_vmxS23BJ5v4Zf84NCH9fw?pwd=y76c 提取码：y76c
> 
> 链接: https://pan.baidu.com/s/1_vmxs23bj5v4zf84nch9fw?pwd=y76c 提取码: y76c
> 
> 运行错误看起来是数据的问题，img_align_celeba的图片大小不固定。
> 
> The run error appears to be a data issue, and IMG images are not fixed in size.

太感谢您的及时回复了
