### ISSUE TITLE
Where is check_points/SPARNetHD_V4_Attn2D/latest_net_H.pth?

### ISSUE THREAD

**Issue by Koruvika** [chaofengc/Face-SPARNet#29]

**Comment by Koruvika** [comment]
latest_net_H.pth seems not in [Github](https://github.com/chaofengc/Face-SPARNet/releases/tag/v0.1.0) and [BaiduNetDisk](https://pan.baidu.com/s/1zYimaAnIgMIKBf9KANpxog). Where's it?

**Comment by chaofengc** [comment]
Please replace it with the correct model path `SPARNetHD_V4_Attn2D_net_H-epoch10.pth` downloaded from [Github release](https://github.com/chaofengc/Face-SPARNet/releases/tag/v0.1.0)
