### ISSUE TITLE
About the preprocess

### ISSUE THREAD

**Issue by tanglei-sys** [chaofengc/Face-SPARNet#5]
Thank you for providing the source code. I want to train the model on the raw CelebA dataset, I would like to ask if there is any code about resizing and cropping. Could face detection codes  be  involved?

**Comment by chaofengc** [comment]
Sorry the preprocess codes are lost. I use MTCNN to detect and crop the face.  You may define proper margins to make sure the whole face is included. Faces larger than 128x128 are included in the training set and resized to 128x128 as ground truth.
