### ISSUE TITLE
get different result by taining on FFHQ

### ISSUE THREAD

**Issue by ningbende** [chaofengc/Face-SPARNet#6]
Thanks for your great job.
I am trying to reproduce the " SPARNetHD_V4_Attn3D" with the "train.py" on datasets FFHQ.
The parameters is just like the  paper, but I cannot get very different result. The images looks mostly bad than  the pretrained model.
Do you have any modification in training?
`
                   device: cuda:1                               [default: None]
                    epoch: latest
              epoch_count: 1
                     g_lr: 0.0001
                 gan_mode: hinge
                  gpu_ids: [1, 0]                               [default: 0]
                     gpus: 2                                    [default: 1]
                   gt_dir: /root/ffhq_data/ffhq_images1024x1024
                init_gain: 0.02
                init_type: normal
                 input_nc: 3
                  isTrain: True                                 [default: None]
                lambda_fm: 10.0
                 lambda_g: 1.0
               lambda_pcp: 1.0
               lambda_pix: 100.0
                load_iter: 0                                    [default: 0]
                load_size: 512
                       lr: 0.0002
           lr_decay_iters: 50
                lr_policy: linear
         max_dataset_size: inf
                    model: sparnethd                            [default: sparnet]
                 n_epochs: 10
           n_epochs_decay: 10
               n_layers_D: 4
                     name: SPARNetHD_V4_Attn3D                  [default: experiment_name]
                      ndf: 64
                      ngf: 64
              niter_decay: 100

`

**Comment by chaofengc** [comment]
All the released models are retrained with the provided scripts in `train.sh`. Would you please show some examples of your results ?

**Comment by ningbende** [comment]
my result： https://github.com/ningbende/Images/blob/main/my_attn3d-FFHQ_.png
the paper：https://github.com/ningbende/Images/blob/main/SPARNetHD_V4_Attn3D_net_H-epoch10.png

I use the code
python train.py --gpus 1 --name SPARNetHD_V4_Attn3D --model sparnethd \
    --Gnorm 'in' --att_name 'spar3d' --g_lr 0.0001 --d_lr 0.0004 --beta1 0.5 --load_size 512 --total_epochs 10 \
    --Dnorm 'in' --num_D 3 --n_layers_D 4 \
    --dataroot /data/vdb/cfchen/FFHQ/imgs1024 --dataset_name ffhq --batch_size 2 \
    --visual_freq 100 --print_freq 10 --save_latest_freq 500 #--continue_train

**Comment by chaofengc** [comment]
The training command seems OK. How long did you train the model ?

**Comment by ningbende** [comment]
6 days   on 2 GPUs( V100)

**Comment by chaofengc** [comment]
OK, I will check the codes and train it again. This takes some time, please stay tuned.

**Comment by ningbende** [comment]
Thank you for your patient, I will try another training without any modification.
Thanks again!

**Comment by chaofengc** [comment]
I directly pull the codes and train the model. Here is the results for the model at 52.5k iteration.
![001](https://user-images.githubusercontent.com/7187685/109380727-9bc95500-7911-11eb-998c-a9187a5ec018.jpg)

The training and test commands are
```
# Train
python train.py --gpus 1 --name SPARNetHD_V4_Attn3D --model sparnethd \
    --Gnorm 'in' --att_name 'spar3d' --g_lr 0.0001 --d_lr 0.0004 --beta1 0.5 --load_size 512 --total_epochs 10 \
    --Dnorm 'in' --num_D 3 --n_layers_D 4 \
    --dataroot ./FFHQ/imgs1024 --dataset_name ffhq --batch_size 2 \
    --visual_freq 100 --print_freq 10 --save_latest_freq 500

# Test
python test_enhance_single_unalign.py --gpus 1 --model sparnethd --name SPARNetHD_V4_Attn3D \
    --res_depth 10 --att_name spar3d --Gnorm 'in' \
    --pretrain_model_path ./check_points/SPARNetHD_V4_Attn3D/latest_net_H.pth \
    --test_img_path ./test_images/test_hzgg.jpg --results_dir test_hzgg_results
```
Because this already demonstrate the correctness of current codes, I will not continue the test training.
Please check your codes to see if you have made any modifications.

**Comment by ningbende** [comment]
thanks for your reply, I will try again
