### ISSUE TITLE
augmentations for SPARNetHD

### ISSUE THREAD

**Issue by t-martyniuk** [chaofengc/Face-SPARNet#7]
why don't you use any of the augmentations you mentioned for SPARNet training except for the "random_gray"?

**Comment by chaofengc** [comment]
SPARNet and SPARNetHD are trained for different purpose. The former is to compare with previous x8 bicubic downsample methods, and the latter is designed to generate high resolution results for real world LQ images. (I believe this has been clearly claimed in the paper)

If you ask for the augmentations of SPARNetHD. The augmentations are implemented here https://github.com/chaofengc/Face-SPARNet/blob/5204283bcb584067a4b28e44231cf8f150cf07a3/data/ffhq_dataset.py#L46
