### ISSUE TITLE
Reproduce accuracy using Helen_test_DIC data

### ISSUE THREAD

**Issue by cli99** [chaofengc/Face-SPARNet#9]
Thanks for sharing the code.
I would like to reproduce the accuracy results for SPARNet and SPARNet-Light.

Do you need to resize the images (16x16) from the Helen test dataset before pass it to SPARNet_S16_V4_Attn2D or SPARNetLight_Attn3D?
Running the corresponding command in test.sh gives me the following error:
RuntimeError: Padding size should be less than the corresponding input dimension, but got: padding (1, 1) at dimension 3 of input [1, 64, 1, 1]
which comes from torch._C._nn.reflection_pad2d(input, pad).

I was able to test SPARNetLight_Attn3D with CelebA-TestN dataset, however, I got a PSNR ~10. Is this expected? Thanks.

**Comment by chaofengc** [comment]
SPARNet and SPARNetHD target at different tasks. SPARNet is trained to upsample a bicubic downsampled 16x16 image to 128x128 image. This is the setting of many previous works.
